[package]
name = "bls-signatures"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]


[dependencies]
pairing = { git = "https://github.com/dignifiedquire/pairing", branch = "hashing" }
ff = "0.4"
rand = "0.4"
rayon = "1"
byteorder = "1.2"
failure = "0.1"

[features]
default = ["pairing/u128-support", "pairing/asm"]
