[package]
name = "bls-signatures"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
edition = "2018"

[dependencies]
pairing = { git = "https://github.com/mmaker/pairing", rev = "a3bbecefe6c5d2f15c7126ea8b84930053929f20" }
ff = "0.4"
rand = "0.4"
rayon = "*"